# -*- coding: utf-8 -*-
"""Actividad Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1snhnXiBjujBE4RJQEZaIECnb_Pb2mrGA
"""

import pandas as pd

from google.colab import files
files.upload()

df=pd.read_excel("BD.xlsx")

df

OrdenColumnas= pd.DataFrame(df, columns = ["Nombre", "Apellido","Categoría","Matrícula","Salario","Fecha ingreso"])
OrdenColumnas

Copiadoras=df[df.Sección == "Copiadoras"]
Copiadoras

Impresoras=df[df.Sección == "Impresoras"]
Impresoras

Fax=df[df.Sección == "Fax"]
Fax

Ingenieria=df[df.Departamento == "Ingeniería"]
Ingenieria

Diseño=df[df.Departamento == "Diseño"]
Diseño

Administracion=df[df.Departamento == "Administración"]
Administracion

Id=df[df.Departamento == "I + D"]
Id

Contabilidad=df[df.Departamento == "Contabilidad"]
Contabilidad

Mercado=df[df.Departamento == "Mercado"]
Mercado

SumaSalario=df.Salario.sum()
SumaSalario